name: 'Comment PR with Deployment URL'
description: 'Posts or updates deployment URL comment on the current PR'

inputs:
  deployment-url:
    description: 'The deployment URL to comment'
    required: true
  github-token:
    description: 'GitHub token with PR write permissions'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Comment on PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          // Get PR number - works for pull_request events
          let pr_number = context.payload.pull_request?.number;
          
          // If not a PR event, try to find PR by branch
          if (!pr_number) {
            const branch = context.ref.replace('refs/heads/', '');
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${branch}`
            });
            
            if (prs.length === 0) {
              console.log(`No open PR found for branch ${branch}`);
              return;
            }
            pr_number = prs[0].number;
          }
          
          const url = '${{ inputs.deployment-url }}';
          const commentBody = `🚀 **Deployment URL**: [${url}](${url})`;
          
          // Get existing comments
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr_number,
          });
          
          // Find existing deployment comment
          const existingComment = comments.find(c => 
            c.body.startsWith('🚀 **Deployment URL**:')
          );
          
          if (existingComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body: commentBody,
            });
            console.log(`Updated comment on PR #${pr_number}`);
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: commentBody,
            });
            console.log(`Created comment on PR #${pr_number}`);
          }
